// sveltekit/src/routes/index.svelte
<script context="module">
    import { useStoryblokApi } from "@storyblok/svelte";

    export async function load() {
        const storyblokApi = useStoryblokApi();
        const { data } = await storyblokApi.get("cdn/stories/home", {
            version: "draft",
        });
        return {
            props: { story: data.story },
        };
    }
</script>

<script>
    import { onMount } from "svelte";
    import { useStoryblokBridge, StoryblokComponent } from "@storyblok/svelte";

    export let story;

    onMount(() => {
        useStoryblokBridge(story.id, (newStory) => (story = newStory));
    });
</script>

<div>
    {#if story}
        <StoryblokComponent blok={story.content} />
    {/if}
</div>

// remix/app/routes/index.jsx
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";

import Layout from "../components/Layout";
import {
  useStoryblokState,
  getStoryblokApi,
  StoryblokComponent,
} from "@storyblok/react";

export const loader = async () => {
  // the slug of the story
  let slug = "home";

  let params = {
    version: "draft", // or 'published'
  };

  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, params);

  return json(data?.story);
};

export default function Page() {
  let story = useLoaderData();

  story = useStoryblokState(story);

  return (
    <Layout>
      <StoryblokComponent blok={story.content} />
    </Layout>
  );
}
