// reactjs/src/components/Grid.js
import { StoryblokComponent, storyblokEditable } from "@storyblok/react";

const Grid = ({ blok }) => {
  return (
    <div style={{display: "flex", justifyContent: "space-around"}} {...storyblokEditable(blok)} className="grid">
      {blok.columns.map((blok) => (
        <StoryblokComponent blok={blok} key={blok._uid} />
      ))}
    </div>
  );
};
 
export default Grid;

// sveltekit/src/components/Grid.svelte
<script>
    import { storyblokEditable, StoryblokComponent } from "@storyblok/svelte";

    export let blok;
</script>

<div use:storyblokEditable={blok} class="flex py-8 mb-6">
    {#each blok.columns as blok}
        <div class="flex-auto px-6">
            <StoryblokComponent {blok} />
        </div>
    {/each}
</div>
